---
- name: Register sshd_config as a variable
  ansible.builtin.slurp:
    src: /etc/ssh/sshd_config
  register: sshd_config
  when: preserve_sshd_config is true

- name: Update installed packages
  ansible.builtin.package:
    name: '*'
    state: latest
  register: is_updated

- name: Reboot the system
  ansible.builtin.include: ../handlers/main.yml
  when: is_updated.changed

- name: Replace sshd_config with previous one
  ansible.builtin.copy:
    content: "{{ sshd_config.content | b64decode }}"
    dest: /tmp/sshd_config
  when: preserve_sshd_config is true
