---
version: 2.1

executors:
  molecule:
    docker:
      - image: ghcr.io/docker-images-mamono210/circleci-executors/molecule-ec2:latest
    resource_class: medium
  trailing-whitespace:
    docker:
      - image: ghcr.io/docker-images-mamono210/circleci-executors/trailing-whitespace:latest
    resource_class: small

orbs:
  ansible-lint: orbss/ansible-lint@0.0.3
  aws-cli: circleci/aws-cli@3.1.1
  molecule-ec2: orbss/molecule-ec2@0.0.7
  yamllint: orbss/yamllint@0.0.4

jobs:
  ansible-lint:
    executor: ansible-lint/default
    steps:
      - checkout
      - ansible-lint/execute:
          molecule-role-test: true
  molecule-ec2:
    executor: molecule
    parameters:
      ansible-user:
        type: string
      aws-ami-id:
        type: string
      aws-instance-type:
        type: string
      aws-resource-name:
        type: string
      aws-vpc-subnet-id:
        type: string
      circleci-timeout:
        type: string
      molecule-scenario-name:
        type: string
    working_directory: ~/centos_update
    steps:
      - checkout
      - aws-cli/setup
      - aws-cli/setup:
          profile-name: default
          role-arn: ${AWS_ROLE_ARN}
          role-session-name: << parameters.aws-resource-name >>
          session-duration: '2100'
      - molecule-ec2/execute:
          ansible-user: << parameters.ansible-user >>
          aws-ami-id: << parameters.aws-ami-id >>
          aws-instance-type: << parameters.aws-instance-type >>
          aws-resource-name: << parameters.aws-resource-name >>
          aws-vpc-subnet-id: << parameters.aws-vpc-subnet-id >>
          circleci-timeout: << parameters.circleci-timeout >>
          molecule-scenario-name: << parameters.molecule-scenario-name >>
  yamllint:
    executor: yamllint/default
    steps:
      - checkout
      - yamllint/execute
  trailing-whitespace:
    executor: trailing-whitespace
    steps:
      - checkout
      - run:
          name: Execute trailing-whitespace
          command: trailing-whitespace

workflows:
  version: 2.1
  build:
    jobs:
      - trailing-whitespace
      - yamllint:
          requires:
            - trailing-whitespace
      - ansible-lint:
          requires:
            - yamllint
      - molecule-ec2:
          ansible-user: centos
          aws-ami-id: 'ami-0b6da95c5acd0be7c'
          aws-instance-type: 't2.medium'
          aws-resource-name: 'circleci_ansible-roles_centos_update_centos7_defaul'
          aws-vpc-subnet-id: 'subnet-022a704b3061b8b39'
          circleci-timeout: '15m'
          molecule-scenario-name: 'default'
          context: aws-oidc
          requires:
            - ansible-lint
      - molecule-ec2:
          ansible-user: centos
          aws-ami-id: 'ami-06f0acf3be02f9f64'
          aws-instance-type: 't4g.medium'
          aws-resource-name: 'circleci_ansible-roles_centos_update_centos-stream8'
          aws-vpc-subnet-id: 'subnet-022a704b3061b8b39'
          circleci-timeout: '15m'
          molecule-scenario-name: 'default'
          context: aws-oidc
          requires:
            - ansible-lint
      - molecule-ec2:
          ansible-user: ec2-user
          aws-ami-id: 'ami-0240506e88917a482'
          aws-instance-type: 't2.medium'
          aws-resource-name: 'circleci_ansible-roles_centos_update_centos-stream9'
          aws-vpc-subnet-id: 'subnet-022a704b3061b8b39'
          circleci-timeout: '15m'
          molecule-scenario-name: 'default'
          context: aws-oidc
          requires:
            - ansible-lint
