---
- name: Create
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Set variables of molecule.yml to molecule_platforms
      ansible.builtin.set_fact:
        molecule_platforms: "{{ molecule_yml.platforms }}"

    - name: Execute
      ansible.builtin.include_role:
        name: mamono210.molecule_ec2_driver
      vars:
        molecule_ec2_driver_resource_state: 'present'
